/**
 * Study-tier resolution. Each TIS jurisdiction publishes (or has
 * a settled practitioner convention for) different deliverable
 * shapes keyed off project size: a Worksheet or Screening Letter
 * for the smallest projects, an Abbreviated / Memo for mid-tier,
 * and a Full TIS / TIA / TA for the largest. This module is the
 * single source of truth that maps (jurisdiction, project) → tier.
 *
 * The renderer dispatch in pdf-export.ts calls resolveStudyTier()
 * and picks the corresponding sub-template. When the caller passes
 * an explicit tier on the TisRequest, that overrides the auto
 * resolution — consultants sometimes need a Worksheet for a project
 * that auto-resolves to Abbreviated (and vice versa) to match a
 * specific jurisdiction's request.
 *
 * Jurisdiction thresholds below reflect the formal published rules
 * captured in REGIONAL-SPECS/{state}-tis-spec.md plus targeted
 * research; sources tagged inline. When a jurisdiction has no
 * formal tier system (IDOT downstate, Cook County, several FL
 * cities), falls back to a sensible default keyed off the ITE peak-
 * hour trip count.
 */
import type { Region } from "./regions";
import type { ResolvedStudyTier, StudyTier } from "./tis";

export type TierInput = {
  /** Daily trips generated by the project (ITE Trip Generation). */
  dailyTrips: number;
  /** PM peak hour trips (used by most US jurisdictions' tier thresholds). */
  pmPeakTrips: number;
  /** Project size in the published independent variable. */
  size: number;
  /** Unit short — "ksf", "du", "rooms", "emp", etc. */
  unit: string;
  /** ITE land use code (used for residential-DU tier rules in Chicago). */
  landUseCode: string;
};

/**
 * Resolve the deliverable tier for a project. When the caller
 * passed an explicit non-auto tier on the request, that is
 * returned verbatim. Otherwise picks per the jurisdiction's
 * formal threshold rules; falls through to a US-default
 * heuristic for unrecognized regions.
 */
export function resolveStudyTier(
  region: Region | null,
  input: TierInput,
  requested?: StudyTier,
): ResolvedStudyTier {
  if (requested && requested !== "auto") return requested;

  const stateCode = region?.stateCode ?? null;
  const country = region?.country ?? "US";

  // --- UK / London Transport Assessment ---------------------------------
  if (country === "UK") return ukTier(input);

  // --- US per-state rules -----------------------------------------------
  if (country === "US" && stateCode) {
    switch (stateCode) {
      case "GA": return gaTier(input);
      case "TX": return txTier(region!, input);
      case "IL": return ilTier(region!, input);
      case "CA": return caTier(input);
      case "FL": return flTier(region!, input);
    }
  }

  return defaultUsTier(input);
}

// ---------- GA ----------
// Gwinnett County DOT's 4-level scheme (TIS Guidelines 2023) is the
// most-copied template in metro Atlanta and the only published GA
// jurisdiction with explicit numeric tiering. Level 1 (0-20 PHT) =
// Worksheet, Level 2 (21-249 PHT) = Abbreviated, Level 3 (250-499 PHT)
// = Full TIS, Level 4 (≥500 PHT OR DRI status) = DRI-level (handled
// separately by probablyDriScale + renderTisGeorgiaDriSections).
// GRTA's parallel naming: <1,000 Net ADT → "Limited Trip Generation
// Memo" (≈ Worksheet); ≥1,000 Net ADT → "TIS". GDOT itself only
// distinguishes >2,000 gross daily trips as the TIS trigger (Driveway
// & Encroachment Control §2D verbatim).
function gaTier(input: TierInput): ResolvedStudyTier {
  const pht = input.pmPeakTrips || estimatePhtFromDaily(input.dailyTrips);
  if (pht <= 20) return "worksheet";  // Gwinnett Level 1
  if (pht <= 249) return "abbreviated"; // Gwinnett Level 2
  return "full";                       // Gwinnett Level 3 (or DRI = Level 4)
}

// ---------- TX ----------
// Each Texas city publishes its own thresholds (TX has no statewide
// numeric trigger; TxDOT TSP Ch. 16 categories drive depth of effort
// on state-system routes). Fort Worth's three-tier worksheet/
// abbreviated/full structure is the cleanest model; Austin's ≥2,000
// vpd trigger gates a full TIA (below which a Determination Worksheet
// applies); San Antonio gates at 75 PHT (UDC §35-502); Houston ≈100
// PHT per the 2023 IDM; Dallas uses practitioner consensus ~100 PHT
// and ~1,000 ADT. (CA Phase 2 research pending finer Austin tiering;
// rules below may refine after.)
function txTier(region: Region, input: TierInput): ResolvedStudyTier {
  const pht = input.pmPeakTrips || estimatePhtFromDaily(input.dailyTrips);
  const daily = input.dailyTrips;
  const name = (region.displayName ?? "").toLowerCase();

  if (name.includes("fort worth")) {
    if (pht < 100 && daily < 1000) return "worksheet";
    if (pht < 300 && daily < 5000) return "abbreviated";
    return "full";
  }
  if (name.includes("austin")) {
    if (daily < 2000) return "worksheet";
    return "full";
  }
  if (name.includes("san antonio")) {
    // UDC §35-502: ≥76 PHT triggers Full TIA. Below 76 PHT, the
    // Peak Hour Trip Generation Form + Turn Lane Assessment is the
    // worksheet shape.
    if (pht < 76) return "worksheet";
    return "full";
  }
  if (name.includes("houston")) {
    if (pht < 100) return "worksheet";
    if (pht < 500) return "abbreviated";
    return "full";
  }
  if (name.includes("dallas")) {
    // Development Code §51A-4.803: 1,000 daily trips gates Full TIS;
    // below that, a Worksheet + optional waiver. No formal abbreviated
    // tier in Dallas — we still expose one for projects that need a
    // mid-shape deliverable by consultant choice.
    if (daily < 1000) return "worksheet";
    if (pht < 500) return "abbreviated";
    return "full";
  }
  // TxDOT statewide TSP Ch. 16: Cat 1 (100-499 PHT), Cat 2 (500-1,000),
  // Cat 3 (>1,000). Mapped to Worksheet / Abbreviated / Full.
  if (pht < 100) return "worksheet";
  if (pht < 500) return "abbreviated";
  return "full";
}

// ---------- IL ----------
// IL has no statewide tier structure. IDOT downstate (D8 Appx. A April
// 2024) is a single monolithic TIS format — no formal worksheet/
// abbreviated tier; we map everything that crosses the warrant-implicit
// trigger to "full" since that's the only published shape. Chicago
// CDOT TDM Guidelines v1.1 (June 2023) defines four tiers — Tier 0
// (no review), Tier 1 (CDOT PRC review only), Tier 2 (TDM Memo), Tier 3
// (full TDM Study + Plan) — with explicit dwelling-unit + sf thresholds
// per use class. McHenry County: 50 ADT triggers a full TIS (Minor
// Access). Cook County, DuPage, Lake, Will, Kane: discretionary, no
// published tier — fall back to PHT heuristic.
function ilTier(region: Region, input: TierInput): ResolvedStudyTier {
  const name = (region.displayName ?? "").toLowerCase();
  const code = input.landUseCode;
  const isResidential = code.startsWith("21") || code.startsWith("22") || code.startsWith("23");
  const isRetail = code.startsWith("82") || code.startsWith("85") || code.startsWith("86") || code.startsWith("87") || code.startsWith("88");
  const isOffice = code.startsWith("71") || code.startsWith("75") || code.startsWith("77");
  const isIndustrial = code.startsWith("11") || code.startsWith("13") || code.startsWith("14") || code.startsWith("15");

  if (name.includes("chicago")) {
    // CDOT TDM Guidelines v1.1 explicit DU + sf thresholds. Only
    // applies inside CCO transit-served B/C/D zoning; this dispatch
    // ignores the geographic gate (the TDM section header in the PDF
    // notes the limitation).
    if (isResidential) {
      const du = input.size;
      if (du < 20) return "worksheet"; // Tier 0 — no review
      if (du <= 50) return "worksheet"; // Tier 1 — site plan only
      if (du <= 175) return "abbreviated"; // Tier 2 — TDM Memo
      return "full"; // Tier 3 — full TDM Study + Plan
    }
    if (isRetail) {
      const sf = input.unit.toLowerCase().includes("ksf") ? input.size * 1000 : input.size;
      if (sf < 10000) return "worksheet";
      if (sf <= 30000) return "worksheet"; // Tier 1
      if (sf <= 75000) return "abbreviated"; // Tier 2
      return "full"; // Tier 3
    }
    if (isOffice) {
      const sf = input.unit.toLowerCase().includes("ksf") ? input.size * 1000 : input.size;
      if (sf < 30000) return "worksheet";
      if (sf <= 50000) return "worksheet"; // Tier 1
      if (sf <= 150000) return "abbreviated"; // Tier 2
      return "full"; // Tier 3
    }
    if (isIndustrial) {
      const sf = input.unit.toLowerCase().includes("ksf") ? input.size * 1000 : input.size;
      if (sf < 50000) return "worksheet";
      // Industrial collapses directly to Tier 2/3 review at >50ksf per
      // CDOT TDM Guidelines Table 1; default to abbreviated unless very
      // large.
      if (sf <= 150000) return "abbreviated";
      return "full";
    }
    // Non-residential, non-retail, non-office, non-industrial:
    // fall through to the trip-count heuristic.
  }

  // McHenry County: 50-ADT Major Access trigger.
  if (name.includes("mchenry")) {
    if (input.dailyTrips < 50) return "worksheet";
    return "full";
  }

  // Otherwise IDOT downstate has no tier structure — D8 Appx. A is a
  // single monolithic format. Use the trip-count heuristic to decide
  // whether the project crosses the warrant-implicit floor; below it,
  // a worksheet-style "no full TIS required" memo is appropriate.
  const pht = input.pmPeakTrips || estimatePhtFromDaily(input.dailyTrips);
  if (pht < 100) return "worksheet";
  if (pht < 500) return "abbreviated";
  return "full";
}

// ---------- CA ----------
// OPR Dec 2018 floor: <110 daily trips presumed less-than-significant
// (the "screened-out" determination = our Worksheet). Jurisdiction
// overlays raise this floor (LA 250, Sacramento 250, Long Beach 500,
// Fresno 500). Above the screen, CA does not formally tier into
// Abbreviated vs Full — the deliverable is a single Transportation
// Study / TIA with CEQA-VMT + non-CEQA Operational LOS sections.
// We use a mid-tier "Abbreviated" for projects in the 110-500 trip
// band as a practitioner convenience.
function caTier(input: TierInput): ResolvedStudyTier {
  if (input.dailyTrips < 110) return "worksheet";
  if (input.dailyTrips < 500) return "abbreviated";
  return "full";
}

// ---------- FL ----------
// Miami-Dade's Level 1/2/3 scheme (<100 / 100-300 / >300 PHT) is the
// most explicit FL tier structure. Tampa uses a 4-tier scheme (De
// Minimis / Adjacent Critical Link / Network Impact / Enhanced
// Network Impact) keyed off 1% of major-roadway link service
// capacity; mapped to worksheet/abbreviated/full with the lowest
// two collapsed into worksheet. Orange County STAMP: 5 PHT
// applicability / 50 PHT ops trigger. Fort Lauderdale + Jacksonville:
// no formal multi-tier — fall back to the FDOT MTSIH planning-vs-
// detailed gradient via the PHT heuristic.
function flTier(region: Region, input: TierInput): ResolvedStudyTier {
  const pht = input.pmPeakTrips || estimatePhtFromDaily(input.dailyTrips);
  const name = (region.displayName ?? "").toLowerCase();

  if (name.includes("miami")) {
    if (pht < 100) return "worksheet"; // Level 1
    if (pht <= 300) return "abbreviated"; // Level 2
    return "full"; // Level 3
  }
  if (name.includes("orlando") || name.includes("orange county")) {
    if (pht <= 5) return "worksheet"; // below STAMP floor
    if (pht <= 50) return "abbreviated"; // STAMP, no ops
    return "full"; // STAMP, ops required
  }
  if (name.includes("tampa")) {
    if (pht < 50) return "worksheet"; // De Minimis
    if (pht < 200) return "abbreviated"; // Adjacent Critical Link
    return "full"; // Network Impact / Enhanced
  }
  if (name.includes("jacksonville")) {
    // Mobility-fee regime — TIA only required for PUD/PD entitlement
    // work, otherwise "pay & go." Treat everything below a large size
    // as worksheet; large projects get full.
    if (input.dailyTrips < 1000) return "worksheet";
    return "full";
  }
  if (name.includes("fort lauderdale")) {
    if (input.dailyTrips < 1000) return "worksheet";
    return "full";
  }
  // FDOT statewide MTSIH gradient — "planning-level" (no pass-by /
  // internal capture) at the low end, "detailed operational" at the
  // top. Tied to Rule 14-96 connection categories: Cat A (1-20 trips/
  // day), Cat B (21-600), Cat C/D (>600).
  if (input.dailyTrips < 100) return "worksheet"; // Cat A or below significant-change
  if (input.dailyTrips < 600) return "abbreviated"; // Cat B
  return "full"; // Cat C/D
}

// ---------- UK ----------
// DfT 2007 Guidance Table 1 / Annex B (still de-facto despite
// withdrawal Oct 2014). Thresholds are size-based per use class, not
// PHT. For residential (C3 dwellings, the most common case): TS at
// 50-80 units, TA above 80 units. For other use classes the size
// is in m² — we approximate using ksf (1 ksf ≈ 92.9 m²) when the
// project size unit matches.
function ukTier(input: TierInput): ResolvedStudyTier {
  const code = input.landUseCode;
  const isResidential = code.startsWith("21") || code.startsWith("22") || code.startsWith("23");
  const isHotel = code === "310" || code === "311" || code === "320" || code === "330";

  if (isResidential) {
    // C3 dwellings: TS 50-80, TA >80
    if (input.size < 50) return "worksheet"; // below TS
    if (input.size <= 80) return "abbreviated"; // TS
    return "full"; // TA
  }
  if (isHotel) {
    // C1 hotels: TS 75-100 bedrooms, TA >100 bedrooms
    if (input.size < 75) return "worksheet";
    if (input.size <= 100) return "abbreviated";
    return "full";
  }

  // For all other use classes, approximate using m² conversion when
  // size is in ksf. DfT bands per use class vary widely (A1 retail
  // TS 250-800 m² / A2 1,000-2,500 / B1 1,500-2,500 / etc.); use
  // a conservative middle ground at ~750 m² TS floor / ~2,000 m²
  // TA threshold for unknown use classes.
  const m2 = input.unit.toLowerCase().includes("ksf") ? input.size * 92.9 : input.size;
  if (m2 < 750) return "worksheet";
  if (m2 <= 2000) return "abbreviated";
  return "full";
}

// ---------- US default ----------
// For regions without a state-specific renderer, fall back to a
// common-practice tier convention.
function defaultUsTier(input: TierInput): ResolvedStudyTier {
  const pht = input.pmPeakTrips || estimatePhtFromDaily(input.dailyTrips);
  if (pht < 100) return "worksheet";
  if (pht < 500) return "abbreviated";
  return "full";
}

/**
 * Rough PHT estimate when the engine output is missing pmPeakTrips
 * (older payloads, or daily-only land uses). ITE convention puts
 * peak hour at roughly 8-10 % of daily; we use 9 % as a midpoint.
 */
function estimatePhtFromDaily(daily: number): number {
  if (!Number.isFinite(daily) || daily <= 0) return 0;
  return Math.round(daily * 0.09);
}

/** Human-readable label for the resolved tier — used in report cover. */
export function tierDisplayLabel(tier: ResolvedStudyTier): string {
  switch (tier) {
    case "worksheet": return "Worksheet / Screening Letter";
    case "abbreviated": return "Abbreviated TIS";
    case "full": return "Full Traffic Impact Study";
  }
}

/**
 * Jurisdiction-specific tier label used in the report cover. Surfaces
 * the formal name the host agency uses (e.g. "GRTA Limited Trip
 * Generation Memo" vs. our generic "Worksheet") so the deliverable
 * matches the submittal expectation.
 */
export function jurisdictionTierLabel(region: Region | null, tier: ResolvedStudyTier): string {
  const country = region?.country ?? "US";
  const stateCode = region?.stateCode ?? null;
  const name = (region?.displayName ?? "").toLowerCase();

  if (country === "UK") {
    switch (tier) {
      case "worksheet": return "Pre-application Transport Scoping Note";
      case "abbreviated": return "Transport Statement (TS)";
      case "full": return "Transport Assessment (TA)";
    }
  }

  if (stateCode === "GA") {
    switch (tier) {
      case "worksheet": return "Gwinnett Level 1 TIS / GRTA Limited Trip Generation Memo";
      case "abbreviated": return "Gwinnett Level 2 TIS — Abbreviated";
      case "full": return "Gwinnett Level 3 TIS — Full Traffic Impact Study";
    }
  }

  if (stateCode === "IL" && name.includes("chicago")) {
    switch (tier) {
      case "worksheet": return "CDOT Tier 1 — Site Plan + PRC Review";
      case "abbreviated": return "CDOT Tier 2 — TDM Project Memo";
      case "full": return "CDOT Tier 3 — Full TDM Study + Plan";
    }
  }

  if (stateCode === "FL" && name.includes("tampa")) {
    switch (tier) {
      case "worksheet": return "Tampa De Minimis Determination";
      case "abbreviated": return "Tampa Adjacent Critical Link & Intersection Analysis";
      case "full": return "Tampa Network Impact Analysis";
    }
  }

  if (stateCode === "FL" && name.includes("miami")) {
    switch (tier) {
      case "worksheet": return "Miami-Dade Level 1 TIA";
      case "abbreviated": return "Miami-Dade Level 2 TIA";
      case "full": return "Miami-Dade Level 3 TIA";
    }
  }

  if (stateCode === "FL" && (name.includes("orlando") || name.includes("orange county"))) {
    switch (tier) {
      case "worksheet": return "Orange County STAMP Applicability Screening";
      case "abbreviated": return "Orange County STAMP Operational TIA";
      case "full": return "Orange County STAMP Full TIA";
    }
  }

  if (stateCode === "FL" && name.includes("jacksonville")) {
    switch (tier) {
      case "worksheet": return "Jacksonville Mobility Fee Worksheet (CMMSO)";
      case "abbreviated": return "Jacksonville Abbreviated TIS (LDPM Vol. 1)";
      case "full": return "Jacksonville Full TIS (LDPM Vol. 1)";
    }
  }

  if (stateCode === "FL" && (name.includes("fort lauderdale") || name.includes("broward"))) {
    switch (tier) {
      case "worksheet": return "Fort Lauderdale / Broward Concurrency-District Worksheet";
      case "abbreviated": return "Broward Concurrency-District Abbreviated TIS";
      case "full": return "Broward Concurrency-District Full TIS";
    }
  }

  if (stateCode === "FL") {
    switch (tier) {
      case "worksheet": return "FDOT MTSIH Planning-Level Analysis";
      case "abbreviated": return "FDOT MTSIH Abbreviated MTIA";
      case "full": return "FDOT MTSIH Full MTIA";
    }
  }

  if (stateCode === "TX") {
    if (name.includes("fort worth")) {
      switch (tier) {
        case "worksheet": return "Fort Worth TIA Worksheet";
        case "abbreviated": return "Fort Worth Abbreviated TIA";
        case "full": return "Fort Worth Full TIA";
      }
    }
    if (name.includes("austin")) {
      switch (tier) {
        case "worksheet": return "Austin TIA Determination Worksheet";
        case "abbreviated": return "Austin TIA Memo";
        case "full": return "Austin Full TIA";
      }
    }
    if (name.includes("san antonio")) {
      switch (tier) {
        case "worksheet": return "San Antonio Peak Hour Trip Generation Form";
        case "abbreviated": return "San Antonio Abbreviated TIA";
        case "full": return "San Antonio Full TIA + Rough Proportionality Determination";
      }
    }
  }

  if (stateCode === "CA") {
    switch (tier) {
      case "worksheet": return "CEQA-VMT Screened-Out Determination Memo";
      case "abbreviated": return "Transportation Analysis — Screening Tier";
      case "full": return "Transportation Analysis — Full VMT + Operational LOS";
    }
  }

  return tierDisplayLabel(tier);
}
