import { Router, type IRouter } from "express";
import {
  ListIntersectionsResponse,
  GetIntersectionResponse,
  GetTrafficSummaryResponse,
  GetInefficiencyRankingsResponse,
  GetZoneBreakdownResponse,
  GetTurnDistributionResponse,
  GetSignalTimingDistributionResponse,
  GetPeakHourLoadResponse,
  GetRecommendationsResponse,
  GetOptimizedScenarioResponse,
  GetAccidentRiskResponse,
  PredictDayBody,
  PredictDayResponse,
  GetLiveIncidentsResponse,
  GetPredictionAccuracyResponse,
  GetLiveWeatherResponse,
  GetTodayAccidentPredictionsResponse,
  GetTodayAccidentPredictionsQueryParams,
  GetLiveTrafficFlowResponse,
  GetLiveHotspotFixesResponse,
  GetDmsSpeedsResponse,
  GetGdotAlertsResponse,
  GetPredictedTrafficFlowResponse,
  GetBacktestReportResponse,
} from "@workspace/api-zod";
import {
  getIntersectionSummaries,
  getIntersectionById,
  getTrafficSummary,
  getInefficiencyRankings,
  getZoneBreakdown,
  getTurnDistribution,
  getSignalTimingDistribution,
  getPeakHourLoad,
  getHourlyLoadFor,
  getRecommendationFor,
  getRecommendations,
  getOptimizedScenario,
  getAccidentRiskBundle,
  predictDay,
  predictTodayAccidents,
} from "../lib/atlanta-analysis";
import { loadRoadNetwork } from "../lib/atlanta-data";
import { getLiveIncidents } from "../lib/atlanta-live";
import { getLiveWeather } from "../lib/atlanta-weather";
import { computeHourlyWeatherMultipliers } from "../lib/atlanta-weather-detail";
import { getLiveTrafficFlow, getLiveHotspotFixes, getPredictedTrafficFlow } from "../lib/atlanta-traffic-flow";
import { getArchiveSummary, getArchiveSeries } from "../lib/atlanta-traffic-archive";
import { getDmsSpeedReadings } from "../lib/atlanta-dms";
import { getGdotAlerts } from "../lib/atlanta-alerts";
import {
  recordSnapshot,
  getAccuracySummary,
  getRecentActivityMultipliers,
  computeBacktestReport,
  type DaySnapshot,
} from "../lib/atlanta-history";
import {
  getParkingSummaryView,
  getAllLotsView,
  getLotByIdView,
  ARCHETYPE_LABELS,
} from "../lib/atlanta-parking";

const router: IRouter = Router();

router.get("/atlanta/intersections", (_req, res): void => {
  res.json(ListIntersectionsResponse.parse(getIntersectionSummaries()));
});

router.get("/atlanta/summary", (_req, res): void => {
  res.json(GetTrafficSummaryResponse.parse(getTrafficSummary()));
});

router.get("/atlanta/rankings", (_req, res): void => {
  res.json(GetInefficiencyRankingsResponse.parse(getInefficiencyRankings()));
});

router.get("/atlanta/zone-breakdown", (_req, res): void => {
  res.json(GetZoneBreakdownResponse.parse(getZoneBreakdown()));
});

router.get("/atlanta/turn-distribution", (_req, res): void => {
  res.json(GetTurnDistributionResponse.parse(getTurnDistribution()));
});

router.get("/atlanta/signal-timing", (_req, res): void => {
  res.json(
    GetSignalTimingDistributionResponse.parse(getSignalTimingDistribution()),
  );
});

router.get("/atlanta/peak-hour-load", (_req, res): void => {
  res.json(GetPeakHourLoadResponse.parse(getPeakHourLoad()));
});

router.get("/atlanta/recommendations", (_req, res): void => {
  res.json(GetRecommendationsResponse.parse(getRecommendations()));
});

router.get("/atlanta/optimized-scenario", (_req, res): void => {
  res.json(GetOptimizedScenarioResponse.parse(getOptimizedScenario()));
});

router.get("/atlanta/accident-risk", (_req, res): void => {
  // No caching — the dataset is regenerated by the preprocess script and we
  // want browsers to always see the latest version (the response is computed
  // once per server boot anyway).
  res.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
  res.setHeader("Pragma", "no-cache");
  res.setHeader("Expires", "0");
  res.json(GetAccidentRiskResponse.parse(getAccidentRiskBundle()));
});

router.post("/atlanta/predict-day", (req, res): void => {
  const parsed = PredictDayBody.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: "Invalid request body", issues: parsed.error.issues });
    return;
  }
  try {
    const result = predictDay(parsed.data);
    res.json(PredictDayResponse.parse(result));
  } catch (e) {
    req.log.error({ err: e }, "predictDay failed");
    res.status(400).json({ error: e instanceof Error ? e.message : String(e) });
  }
});

// ---------- Predicted traffic flow (tomorrow's road map) ----------

router.get("/atlanta/predicted-traffic-flow", async (req, res): Promise<void> => {
  const date = String(req.query.date ?? "");
  const hourRaw = Number(req.query.hour);
  if (!date || !/^\d{4}-\d{2}-\d{2}$/.test(date)) {
    res.status(400).json({ error: "date query param required (YYYY-MM-DD)" });
    return;
  }
  if (!Number.isFinite(hourRaw) || hourRaw < 0 || hourRaw > 23) {
    res.status(400).json({ error: "hour query param required (0-23)" });
    return;
  }
  const weatherRaw = String(req.query.weather ?? "clear");
  const weather = (["clear", "light_rain", "heavy_rain", "snow"].includes(weatherRaw)
    ? weatherRaw
    : "clear") as "clear" | "light_rain" | "heavy_rain" | "snow";
  const events = {
    schoolDay: req.query.schoolDay === "true",
    falconsHome: req.query.falconsHome === "true",
    hawksHome: req.query.hawksHome === "true",
    bravesHome: req.query.bravesHome === "true",
    gtFootball: req.query.gtFootball === "true",
    holiday: req.query.holiday === "true",
  };
  const classesRaw = String(req.query.classes ?? "0,1,2");
  const classes = classesRaw.split(",").map(Number).filter((n) => Number.isInteger(n) && n >= 0 && n <= 3);
  if (classes.length === 0) classes.push(0, 1, 2);

  // When the user explicitly picked a weather scenario from the UI, respect
  // that choice (use the discrete bucket multiplier). Otherwise — and ONLY
  // when the requested date is today's date in Atlanta — replace the bucket
  // with the continuous per-hour multipliers from Open-Meteo. The live feed
  // requests `forecast_days=1` so its hourly array only covers today;
  // applying it to tomorrow/future dates would attribute today's weather
  // pattern to the wrong day.
  let hourlyWeatherMults: number[] | undefined;
  const userPickedWeather = typeof req.query.weather === "string"
    && req.query.weather !== "clear";
  if (!userPickedWeather && date === todayInAtlanta()) {
    try {
      const wx = await getLiveWeather();
      hourlyWeatherMults = computeHourlyWeatherMultipliers(wx);
    } catch (e) {
      req.log.warn({ err: e }, "predicted-traffic-flow: weather fetch failed, using bucket fallback");
    }
  }

  try {
    const bundle = getPredictedTrafficFlow({
      date,
      weather,
      events,
      hour: Math.trunc(hourRaw),
      classes,
      hourlyWeatherMults,
    });
    res.json(GetPredictedTrafficFlowResponse.parse(bundle));
  } catch (e) {
    req.log.error({ err: e }, "predicted-traffic-flow failed");
    res.status(500).json({ error: e instanceof Error ? e.message : String(e) });
  }
});

// ---------- GDOT 511 DMS speeds + Alerts (require API key) ----------

router.get("/atlanta/dms-speeds", async (req, res): Promise<void> => {
  try {
    const bundle = await getDmsSpeedReadings();
    res.json(GetDmsSpeedsResponse.parse(bundle));
  } catch (e) {
    req.log.error({ err: e }, "dms-speeds fetch failed");
    res.status(502).json({
      error: "Failed to fetch DMS speeds from GDOT 511 API",
      detail: e instanceof Error ? e.message : String(e),
    });
  }
});

router.get("/atlanta/alerts", async (req, res): Promise<void> => {
  try {
    const bundle = await getGdotAlerts();
    res.json(GetGdotAlertsResponse.parse(bundle));
  } catch (e) {
    req.log.error({ err: e }, "gdot-alerts fetch failed");
    res.status(502).json({
      error: "Failed to fetch alerts from GDOT 511 API",
      detail: e instanceof Error ? e.message : String(e),
    });
  }
});

// ---------- Live Atlanta-metro incidents (GDOT 511 v2 API / legacy fallback) ----------

router.get("/atlanta/live-incidents", async (req, res): Promise<void> => {
  res.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
  res.setHeader("Pragma", "no-cache");
  res.setHeader("Expires", "0");
  try {
    const bundle = await getLiveIncidents();
    res.json(GetLiveIncidentsResponse.parse(bundle));
  } catch (e) {
    req.log.error({ err: e }, "live-incidents fetch failed");
    res.status(502).json({
      error: "Failed to fetch live incidents from upstream 511ga.org",
      detail: e instanceof Error ? e.message : String(e),
    });
  }
});

// ---------- GDOT 511 archive (proprietary time-series accumulation) ----------
//
// Public, read-only summary + series of the snapshots persisted by the
// background archive worker. Data accumulates from server boot forward;
// there is no historical backfill upstream. Useful for showing reviewers
// "we have N days of continuous incident history for the corridor".

router.get("/atlanta/traffic-flow/history", async (req, res): Promise<void> => {
  // Public endpoint, but always cache-busted because the underlying table
  // grows monotonically.
  res.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
  try {
    const since = typeof req.query["since"] === "string" ? req.query["since"] : undefined;
    const until = typeof req.query["until"] === "string" ? req.query["until"] : undefined;
    const limitRaw = typeof req.query["limit"] === "string" ? Number(req.query["limit"]) : 500;
    const limit = Number.isFinite(limitRaw) ? Math.min(Math.max(limitRaw, 1), 2000) : 500;
    const [summary, series] = await Promise.all([
      getArchiveSummary(since, until),
      getArchiveSeries(since, until, limit),
    ]);
    res.json({ summary, series });
  } catch (e) {
    req.log.error({ err: e }, "traffic-archive.history_failed");
    res.status(500).json({
      error: "Failed to read traffic archive",
      detail: e instanceof Error ? e.message : String(e),
    });
  }
});

// Returns today's accuracy snapshot (predicted top-N vs signals that actually
// saw a live incident today), updates the persisted history file, and includes
// the rolling 7-day stats. The snapshot also drives the per-signal recent-
// activity multiplier baked into future predictDay() calls.
router.get("/atlanta/accuracy", async (req, res): Promise<void> => {
  res.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
  res.setHeader("Pragma", "no-cache");
  res.setHeader("Expires", "0");
  try {
    const topNRaw = Number(req.query.topN);
    const topN = Number.isFinite(topNRaw)
      ? Math.max(10, Math.min(1000, Math.trunc(topNRaw)))
      : 50;

    // 1) Pull today's live incidents (cached server-side for 90s).
    const live = await getLiveIncidents();

    // 1a) Degraded-mode guard: if the upstream live feed has clearly failed
    //     (zero items in metro AND zero total fetched), do NOT persist a
    //     misleading "0 incidents today" snapshot — that would corrupt the
    //     7-day rolling stats and starve the recent-activity feedback loop.
    //     Surface the degradation honestly to the caller.
    const upstreamDegraded = live.totalFetched === 0;
    if (upstreamDegraded) {
      // Return last-good summary if we have history, otherwise a clear empty
      // report. Either way, do not call recordSnapshot for today.
      const summary = getAccuracySummary(todayInAtlanta());
      const todayDate = todayInAtlanta();
      const placeholder: DaySnapshot = {
        date: todayDate,
        observedAt: new Date().toISOString(),
        predictedTopRiskOsmIds: [],
        topNUsed: 0,
        actualIncidentSignalCounts: {},
        actualIncidentTotal: 0,
        hits: 0,
        hitRatePct: 0,
        precisionPct: 0,
      };
      const report = {
        today: placeholder,
        recentDays: summary.recentDays,
        rollingHitRatePct: summary.rollingHitRatePct,
        rollingPrecisionPct: summary.rollingPrecisionPct,
        liveIncidentsTotal: 0,
        liveIncidentsSnapped: 0,
        recentActivitySignalCount: getRecentActivityMultipliers().size,
        upstreamDegraded: true,
      };
      req.log.warn(
        { fetchedAt: live.fetchedAt },
        "accuracy: upstream live feed returned 0 items — skipping snapshot persistence",
      );
      res.status(200).json(GetPredictionAccuracyResponse.parse(report));
      return;
    }

    // 2) Compute today's prediction with a sensible default scenario:
    //    live weather (continuous hourly multipliers), school day if
    //    weekday, no special events. Using continuous weather here gives
    //    the prediction the same precip/wind/temp signal that the predicted
    //    traffic flow uses, so the accuracy hit rate measures the actual
    //    deployed model — not a "clear weather" approximation of it.
    const todayDate = todayInAtlanta();
    const dow = new Date(`${todayDate}T12:00:00Z`).getUTCDay();
    const isWeekday = dow >= 1 && dow <= 5;
    let liveHourlyWeatherMults: number[] | undefined;
    let liveCondition: "clear" | "light_rain" | "heavy_rain" | "snow" = "clear";
    try {
      const wx = await getLiveWeather();
      liveCondition = wx.condition;
      liveHourlyWeatherMults = computeHourlyWeatherMultipliers(wx);
    } catch (e) {
      req.log.warn({ err: e }, "accuracy: weather fetch failed, falling back to clear");
    }
    const prediction = predictDay({
      date: todayDate,
      weather: liveCondition,
      events: { schoolDay: isWeekday },
      hourlyWeatherMults: liveHourlyWeatherMults,
    });

    // 3) Build predicted top-N OSM ids (the model's "high-risk shortlist").
    //    Sort the full signal list ONCE, dedupe FIRST, then slice to exactly
    //    topN — otherwise duplicates between prediction.topWorst and the full
    //    sorted list consume slots and shrink topNUsed below the requested
    //    value (deflating the precision denominator and confusing the UI).
    const sortedAll = [...prediction.signals].sort(
      (a, b) => b.predictedPeakScore - a.predictedPeakScore,
    );
    const seenIds = new Set<number>();
    const uniqueTopRisk: number[] = [];
    for (const s of sortedAll) {
      const osmId = Number(s.id.replace(/^ATL-/, ""));
      if (!Number.isFinite(osmId) || seenIds.has(osmId)) continue;
      seenIds.add(osmId);
      uniqueTopRisk.push(osmId);
      if (uniqueTopRisk.length >= topN) break;
    }

    // 4) Aggregate today's actual incidents per snapped signal.
    const actualCounts: Record<string, number> = {};
    for (const inc of live.incidents) {
      if (!inc.signalId) continue;
      const osmIdStr = String(Number(inc.signalId.replace(/^ATL-/, "")));
      actualCounts[osmIdStr] = (actualCounts[osmIdStr] ?? 0) + 1;
    }
    const actualSignalIds = new Set(Object.keys(actualCounts).map(Number));
    const topRiskSet = new Set(uniqueTopRisk);
    let hits = 0;
    for (const id of actualSignalIds) if (topRiskSet.has(id)) hits++;
    const denomHit = actualSignalIds.size || 0;
    const hitRatePct = denomHit > 0 ? Math.round((hits / denomHit) * 1000) / 10 : 0;
    const precisionPct = uniqueTopRisk.length > 0
      ? Math.round((hits / uniqueTopRisk.length) * 1000) / 10
      : 0;

    // 5) Persist (upsert) today's snapshot.
    const snapshot: DaySnapshot = {
      date: todayDate,
      observedAt: new Date().toISOString(),
      predictedTopRiskOsmIds: uniqueTopRisk,
      topNUsed: uniqueTopRisk.length,
      actualIncidentSignalCounts: actualCounts,
      actualIncidentTotal: live.incidents.length,
      hits,
      hitRatePct,
      precisionPct,
    };
    recordSnapshot(snapshot);

    // 6) Assemble the accuracy report (today + recent days + rolling stats).
    const summary = getAccuracySummary(todayDate);
    const report = {
      today: snapshot,
      recentDays: summary.recentDays,
      rollingHitRatePct: summary.rollingHitRatePct,
      rollingPrecisionPct: summary.rollingPrecisionPct,
      liveIncidentsTotal: live.incidents.length,
      liveIncidentsSnapped: live.snappedToSignal,
      recentActivitySignalCount: getRecentActivityMultipliers().size,
      upstreamDegraded: false,
    };
    res.json(GetPredictionAccuracyResponse.parse(report));
  } catch (e) {
    req.log.error({ err: e }, "accuracy compute failed");
    res.status(502).json({
      error: "Failed to compute prediction accuracy",
      detail: e instanceof Error ? e.message : String(e),
    });
  }
});

// ---------- Backtest credibility report (model accuracy sales sheet) ----------

router.get("/atlanta/backtest-report", (req, res): void => {
  res.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
  res.setHeader("Pragma", "no-cache");
  res.setHeader("Expires", "0");
  try {
    const totalSignals = getIntersectionSummaries().length;
    const report = computeBacktestReport({ totalSignalsInModel: totalSignals });
    res.json(GetBacktestReportResponse.parse(report));
  } catch (e) {
    req.log.error({ err: e }, "backtest-report failed");
    res.status(500).json({
      error: "Failed to compute backtest report",
      detail: e instanceof Error ? e.message : String(e),
    });
  }
});

// ---------- Live Atlanta weather (Open-Meteo, no API key) ----------

router.get("/atlanta/live-weather", async (req, res): Promise<void> => {
  res.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
  res.setHeader("Pragma", "no-cache");
  res.setHeader("Expires", "0");
  try {
    const weather = await getLiveWeather();
    res.json(GetLiveWeatherResponse.parse(weather));
  } catch (e) {
    req.log.error({ err: e }, "live-weather fetch failed");
    res.status(502).json({
      error: "Failed to fetch live weather from Open-Meteo",
      detail: e instanceof Error ? e.message : String(e),
    });
  }
});

// ---------- Apple-Maps-style live traffic flow (synthesized, no API key) ----------

router.get("/atlanta/live-traffic-flow", async (req, res): Promise<void> => {
  try {
    const raw = typeof req.query.classes === "string" ? req.query.classes : "";
    const classes = raw
      .split(",")
      .map((s) => Number(s.trim()))
      .filter((n) => Number.isInteger(n) && n >= 0 && n <= 3);
    const bundle = await getLiveTrafficFlow(classes.length ? { classes } : undefined);
    // Allow conditional GETs to short-circuit with a 304: the bundle's
    // fetchedAt + classes set + segment count uniquely identifies the
    // payload, and it only changes when our 60s server cache rolls. This
    // saves the ~3MB body on the common case where the client polls inside
    // the same minute as a previous request (refresh, second tab, etc).
    const classKey = classes.length ? classes.slice().sort().join(",") : "default";
    const etag = `W/"ltf-${classKey}-${bundle.fetchedAt}-${bundle.segments.length}"`;
    res.setHeader("ETag", etag);
    res.setHeader("Last-Modified", new Date(bundle.fetchedAt).toUTCString());
    // 60s freshness matches our internal cache TTL; require revalidation
    // afterwards so clients always pick up the new compute when it lands.
    res.setHeader("Cache-Control", "private, max-age=60, must-revalidate");
    if (req.headers["if-none-match"] === etag) {
      res.status(304).end();
      return;
    }
    res.json(GetLiveTrafficFlowResponse.parse(bundle));
  } catch (e) {
    req.log.error({ err: e }, "live-traffic-flow failed");
    res.status(500).json({
      error: "Failed to compute live traffic flow",
      detail: e instanceof Error ? e.message : String(e),
    });
  }
});

// ---------- Live signal-timing fixes for crash-prone congested hotspots ----------

router.get("/atlanta/live-hotspot-fixes", async (req, res): Promise<void> => {
  try {
    const bundle = await getLiveHotspotFixes();
    // Same conditional-GET pattern as /live-traffic-flow: 60s server cache,
    // identity = (fetchedAt, total fixes). Keeps the front-end's "Suggest
    // signal fixes" button cheap on repeat clicks.
    const etag = `W/"hsf-${bundle.fetchedAt}-${bundle.fixes.length}"`;
    res.setHeader("ETag", etag);
    res.setHeader("Last-Modified", new Date(bundle.fetchedAt).toUTCString());
    res.setHeader("Cache-Control", "private, max-age=60, must-revalidate");
    if (req.headers["if-none-match"] === etag) {
      res.status(304).end();
      return;
    }
    res.json(GetLiveHotspotFixesResponse.parse(bundle));
  } catch (e) {
    req.log.error({ err: e }, "live-hotspot-fixes failed");
    res.status(500).json({
      error: "Failed to compute live hotspot fixes",
      detail: e instanceof Error ? e.message : String(e),
    });
  }
});

// ---------- Parking pressure (modeled, OSM-sourced inventory) ----------
//
// All three endpoints share an in-memory snapshot keyed to the current minute,
// so 13K-lot computations don't re-run on every request burst.

router.get("/atlanta/parking/summary", (req, res): void => {
  const forceSurge = req.query.forceSurge === "true" || req.query.forceSurge === "1";
  res.setHeader("Cache-Control", "public, max-age=60");
  res.json(getParkingSummaryView(forceSurge));
});

router.get("/atlanta/parking/lots", (req, res): void => {
  const forceSurge = req.query.forceSurge === "true" || req.query.forceSurge === "1";

  let minCapacity = req.query.minCapacity !== undefined
    ? parseInt(String(req.query.minCapacity), 10)
    : NaN;
  if (Number.isFinite(minCapacity) && minCapacity < 0) {
    // Mirror the OpenAPI `minimum: 0` constraint at runtime.
    res.status(400).json({ error: "minCapacity must be >= 0" });
    return;
  }

  const maxFillPct = req.query.maxFillPct !== undefined
    ? parseFloat(String(req.query.maxFillPct))
    : NaN;
  if (Number.isFinite(maxFillPct) && (maxFillPct < 0 || maxFillPct > 100)) {
    res.status(400).json({ error: "maxFillPct must be between 0 and 100" });
    return;
  }

  const archetype = typeof req.query.archetype === "string" ? req.query.archetype : null;
  if (archetype !== null && !(ARCHETYPE_LABELS as readonly string[]).includes(archetype)) {
    res.status(400).json({ error: "Invalid archetype" });
    return;
  }

  let lots = getAllLotsView(forceSurge);
  if (Number.isFinite(minCapacity)) lots = lots.filter((l) => l.capacity >= minCapacity);
  if (Number.isFinite(maxFillPct)) lots = lots.filter((l) => l.fillPct <= maxFillPct);
  if (archetype) lots = lots.filter((l) => l.archetype === archetype);
  res.setHeader("Cache-Control", "public, max-age=60");
  res.json(lots);
});

// Single-lot detail: same minute-snapshot backs the base values, so it stays
// consistent with the map/list. `forceSurge` is honored from query string so
// the demo toggle in the UI keeps detail values aligned with the aggregate
// view (it's intentionally undocumented in OpenAPI to avoid an orval
// path+query name collision; the UI calls it via the typed hook with an
// extra header that the orval client passes through transparently).
router.get("/atlanta/parking/lots/:id", (req, res): void => {
  const forceSurge =
    req.query.forceSurge === "true" ||
    req.query.forceSurge === "1" ||
    req.headers["x-force-surge"] === "1";
  const detail = getLotByIdView(req.params.id, forceSurge);
  if (!detail) {
    res.status(404).json({ error: "Lot not found" });
    return;
  }
  res.setHeader("Cache-Control", "public, max-age=60");
  res.json(detail);
});

// ---------- Today's predicted accident hotspots ----------
//
// Auto-uses the live Atlanta weather and the recent-activity feedback loop.
router.get("/atlanta/today-accident-predictions", async (req, res): Promise<void> => {
  res.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
  res.setHeader("Pragma", "no-cache");
  res.setHeader("Expires", "0");
  try {
    // Normalize the includePastHours query before Zod parses it: orval emits
    // `zod.coerce.boolean()` which treats any non-empty string as true (so
    // "false" would become true). Mapping to a real boolean here keeps the
    // parsed schema honest for the rest of the handler.
    const rawInclude = req.query.includePastHours;
    const includePastBool = rawInclude === "true" || rawInclude === "1";
    const parsed = GetTodayAccidentPredictionsQueryParams.safeParse({
      topN: req.query.topN,
      includePastHours: includePastBool,
    });
    if (!parsed.success) {
      res.status(400).json({
        error: "Invalid query parameters",
        detail: parsed.error.issues.map((i) => `${i.path.join(".")}: ${i.message}`).join("; "),
      });
      return;
    }
    const { topN, includePastHours } = parsed.data;

    // Live weather drives the model — degrade gracefully to "clear" if the
    // upstream is unreachable so we still return a useful prediction. When
    // available, we ALSO derive a 24-element continuous multiplier from the
    // hourly precip/wind/temp outlook so per-hour predictions reflect when
    // bad weather actually arrives, not just a single all-day bucket.
    let weather: "clear" | "light_rain" | "heavy_rain" | "snow" = "clear";
    let weatherSummary = "clear (weather feed unavailable)";
    let hourlyWeatherMults: number[] | undefined;
    try {
      const wx = await getLiveWeather();
      weather = wx.condition;
      weatherSummary = wx.summary;
      hourlyWeatherMults = computeHourlyWeatherMultipliers(wx);
    } catch (e) {
      req.log.warn({ err: e }, "today-accident-predictions: weather fetch failed, defaulting to clear");
    }

    const todayDate = todayInAtlanta();
    const dow = new Date(`${todayDate}T12:00:00Z`).getUTCDay();
    const isWeekday = dow >= 1 && dow <= 5;
    const currentHourLocal = currentHourInAtlanta();

    const result = predictTodayAccidents({
      date: todayDate,
      weather,
      weatherSummary,
      events: { schoolDay: isWeekday },
      topN,
      includePastHours,
      currentHourLocal,
      hourlyWeatherMults,
    });
    res.json(GetTodayAccidentPredictionsResponse.parse(result));
  } catch (e) {
    req.log.error({ err: e }, "today-accident-predictions failed");
    res.status(500).json({
      error: "Failed to compute today's accident predictions",
      detail: e instanceof Error ? e.message : String(e),
    });
  }
});

// Current hour-of-day in America/New_York (0..23).
function currentHourInAtlanta(): number {
  const fmt = new Intl.DateTimeFormat("en-US", {
    timeZone: "America/New_York",
    hour: "numeric",
    hour12: false,
  });
  const parts = fmt.formatToParts(new Date());
  const h = parts.find((p) => p.type === "hour")?.value;
  const n = h ? Number(h) : new Date().getHours();
  // "24" can show up at midnight in some Node versions; normalize.
  return ((n % 24) + 24) % 24;
}

// Today's date in America/New_York as YYYY-MM-DD. Uses Intl to handle DST.
function todayInAtlanta(): string {
  const fmt = new Intl.DateTimeFormat("en-CA", {
    timeZone: "America/New_York",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  });
  return fmt.format(new Date());
}

// Road network is large (~2.6MB) but cached and gzip-compressed (~640KB on the wire).
// Stream it without zod parse — the schema is opaque tuples, not worth validating round-trip.
// Tag with a strong ETag-like header and long-lived cache so browsers don't refetch on
// every reload; the underlying file is regenerated only when we re-import OSM data.
router.get("/atlanta/roads", (_req, res): void => {
  res.setHeader("Cache-Control", "public, max-age=86400, immutable");
  res.json(loadRoadNetwork());
});

router.get("/atlanta/intersections/:id", (req, res): void => {
  const rawId = Array.isArray(req.params.id) ? req.params.id[0] : req.params.id;
  if (!rawId) {
    res.status(400).json({ error: "Intersection id is required" });
    return;
  }
  const intersection = getIntersectionById(rawId);
  if (!intersection) {
    res.status(404).json({ error: "Intersection not found" });
    return;
  }
  res.json(
    GetIntersectionResponse.parse({
      intersection,
      hourlyLoad: getHourlyLoadFor(intersection),
      recommendation: getRecommendationFor(intersection),
    }),
  );
});

export default router;
