import { sql } from "drizzle-orm";
import {
  index,
  jsonb,
  pgTable,
  text,
  timestamp,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";
import { firmsTable } from "./firms";
import { tisProjectsTable } from "./tis-projects";
import { usersTable } from "./auth";

/**
 * Post-build verification enrollments. A firm enrolls a completed
 * project (typically a TIS) for continuous monitoring after the
 * development opens. Every 30 days a comparison report is generated
 * against the accumulating live-traffic time-series, letting the firm
 * tell their developer client "the forecast was within X% of reality."
 *
 * Distinct from a study: a study is one-time, dated, immutable. A
 * monitoring enrollment is an ongoing relationship.
 */
export const monitoringEnrollmentsTable = pgTable(
  "monitoring_enrollments",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    firmId: uuid("firm_id")
      .notNull()
      .references(() => firmsTable.id, { onDelete: "cascade" }),
    // The TIS (or other study) being monitored. ON DELETE SET NULL so
    // dropping the project preserves the monitoring history.
    projectId: uuid("project_id").references(() => tisProjectsTable.id, {
      onDelete: "set null",
    }),
    // Required even if project gets deleted — gives us a friendly name
    // for the enrollment.
    label: text("label").notNull(),
    // Site geometry the analyzer uses to fetch live data.
    siteLat: text("site_lat").notNull(),
    siteLon: text("site_lon").notNull(),
    // What we're verifying: the forecast snapshot captured at enrollment.
    forecastSnapshot: jsonb("forecast_snapshot").notNull(),
    // 'active' while we generate monthly reports; 'paused' when the firm
    // pauses billing; 'completed' after the agreed term (e.g. 24 months).
    status: varchar("status", { length: 16 }).notNull().default("active"),
    enrolledByUserId: varchar("enrolled_by_user_id").notNull(),
    enrolledAt: timestamp("enrolled_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    // The earliest moment we should produce the first comparison.
    expectedOpenDate: timestamp("expected_open_date", { withTimezone: true }),
    lastReportAt: timestamp("last_report_at", { withTimezone: true }),
    notes: text("notes"),
  },
  (table) => [
    index("IDX_monitoring_firm").on(table.firmId),
    index("IDX_monitoring_project").on(table.projectId),
  ],
);

export type MonitoringEnrollment = typeof monitoringEnrollmentsTable.$inferSelect;
export type InsertMonitoringEnrollment = typeof monitoringEnrollmentsTable.$inferInsert;

/**
 * One comparison row per (enrollment, period). Generated by the monthly
 * monitoring job. Holds the forecast-vs-actual delta and the engineer-
 * facing narrative.
 */
export const monitoringReportsTable = pgTable(
  "monitoring_reports",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    enrollmentId: uuid("enrollment_id")
      .notNull()
      .references(() => monitoringEnrollmentsTable.id, { onDelete: "cascade" }),
    periodStart: timestamp("period_start", { withTimezone: true }).notNull(),
    periodEnd: timestamp("period_end", { withTimezone: true }).notNull(),
    payload: jsonb("payload").notNull(),
    // Audit user who triggered an on-demand re-run; null for scheduled.
    generatedByUserId: varchar("generated_by_user_id")
      .references(() => usersTable.id, { onDelete: "set null" }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  (table) => [
    index("IDX_monitoring_reports_enrollment").on(table.enrollmentId, table.createdAt),
  ],
);

export type MonitoringReport = typeof monitoringReportsTable.$inferSelect;
export type InsertMonitoringReport = typeof monitoringReportsTable.$inferInsert;
